# configuration file for sample development environment.  You should clone this into your
# own developer specific config so that nothing gets checked into the repository.

# Logging information...

# Flags to control API serialization. Generally these are just configuration options to
# enable human readable extensions to the APIs to make working with them less painful.
serialization:
  json:
    # Pretty print json
    pretty: true
    # Sort keys alphabetically
    canonical: true
